alias vsa="systemctl status StarWindVSA"
alias vsa_run_rescan="/opt/StarWind/StarWindVSA/drive_c/StarWind/hba_rescan.ps1"
alias vsa_rescan="nano /opt/StarWind/StarWindVSA/drive_c/StarWind/hba_rescan.ps1"
alias vsa_download="sudo wget https://ovf.starwind.com/tmplink/starwind-update.tar.gz --no-check-certificate; sudo tar -xf starwind-update.tar.gz; rm -f starwind-update.tar.gz"
alias vsa_start="systemctl start StarWindVSA"
alias vsa_stop="systemctl stop StarWindVSA"
alias vsa_io="/opt/StarWind/StarWindVSA/drive_c/StarWind/script-io.sh"
alias vsa_management_ip="sudo /opt/StarWind/StarWindVSA/drive_c/StarWind/setup-mngt-ip.sh"
